# Generated by Django 2.2.12 on 2022-05-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0003_userlogin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='branch',
            field=models.CharField(default='CS', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='company',
            field=models.CharField(default='IITM', max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
    ]
