# Generated by Django 2.2.12 on 2022-05-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0004_auto_20220518_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='user_age',
        ),
    ]
