# Generated by Django 2.2.12 on 2022-05-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entriesmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
